name: Master Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build docker image
    runs-on: [self-hosted, buildRunner]
    defaults:
      run:
        working-directory: Docker
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        run: docker compose build
      -
        name: Deploy
        run: docker compose push
  deploy:
    name: Deploy docker image to server
    runs-on: [self-hosted, buildRunner]
    defaults:
      run:
        working-directory: Docker
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set Release Version
        run: echo "RELEASE_VERSION=${{ github.sha }}" >> $GITHUB_ENV
      -
        name: Down exists docker container
        run: docker compose -f docker-compose-deploy.yaml down || true
      -
        name: Run new docker container
        run: docker compose -f docker-compose-deploy.yaml up -d || true